statds/ids-s25

- index.qmd
I added two bullets describing my goals for this course in the Wishlist section of index.qmd
> Mo Mundi added first two wishlist items for index.qmd

- index.qmd
followed along with in-class demo
> added to sebastian wishlist

- index.qmd
Started my wishlist with four wishes.
> Ethan added four wishes to wishlist

- index.qmd
Added two wishes under Alyssa Horn in index.qmd
> Alyssa Horn added two wishes to wishlist

- index.qmd
Assignment 3
Noah added to the Wishlist in file index.qmd of cloned ids-s25 repository.
1. Forked ids-s25 repository.
2. Cloned forked repository to own machine using SSH key.
3. Created a branch nmk_branch using: 'git checkout nmk_branch'.
4. Edited index.qmd file in branched, cloned ids-s25 repository.
5. Added updated file: w/ 'git add index.qmd'.
6. Added multiple commits (10 commits) during process.
7. Pushed changes to github: w/ 'git push origin nmk_branch'.
8. Created a pull request.
> Noah's edited Wishlist for STAT5255: Assignment 3

- index.qmd
Hello,
I have added my wish list to the class notes, index.qmd.
Thanks,
Mezmur
> Mezmur added wish list to class notes

- index.qmd
I added my three wishes in the class roster of the class notes using the Kyle_Reed branch I created.
> Three Wishes, Kyle Reed

- exercises.qmd
- index.qmd
- rosters/3255.txt
Add two wishes to wishlist in index.qmd
Add Xu,Peiwen to 3255.txt in the rosters folder
Fix typo: "informativ emessage" → "informative message" in exercises.qmd
> Add wishes to wishlist, update roster 3255, and fix typo in exercises.qmd

- index.qmd
Classnotes contribution - wishlist update
> Classnotes wishlist update - Luke Roy

- index.qmd
Typo fix in Luke Roy wishlist - accounting
> Typo fix - Luke Roy

- index.qmd
I added my 7 wishes to the Wishlist section in the class notes with 10 informative comments.
> Shiyi Li added 7 wishes to the Wishlist

- index.qmd
Updated the wishlist with 2-wishes
> Updating the Wishlist - Amer El Zein

- index.qmd
Presentation topic choice plus presentation order update - swapping Luke Roy and Ammar Alsadadi
> Order Update and Topic Choice - Luke Roy

- index.qmd
gaofei add wishlist and presentation topic
> gaofei add wishlist and presentation topic

- index.qmd
Hello, 
Mezmur added presentation topic.
Thank you,
Mezmur
> added Mezmur Presentation Topic

- index.qmd
Pushing the name of the topic I am going to present (Folium library)
> Vlad adding the name of topic presentation

- index.qmd
Hello Prof. Yan, I modified the topic that I would like to present. Instead of a Gaussian Regression, I would like to do a basic introduction to Neural Networks instead.
> Ajeeth modified his presentation topic

- index.qmd
Requested SMOTE as topic presentation for Ethan L.
> Added SMOTE for topic presentation, Ethan

- _pandas.qmd
After reviewing all branches, I made two improvements in the introduction for clarity and organization. I also revised the pandas section to fix errors and improve the explanation of key concepts.
> Lang re-worked on pandas notes

- index.qmd
Add topic - "Developing a Python package" to the table in the index.qmd file.
> Peiwen added presentation topic

- index.qmd
This pull request adds my topic presentation on K-Prototypes Clustering to the topic presentation schedule.
> added k-prototypes to topic presentation schedule

- _quarto.yml
- _sentiment_analysis.qmd
- references.bib
1. Added a sentiment analysis section
2. Added author name in quarto.yml
3. Added the references for Ammar's section
> Adding Sentiment Analysis with Python for Ammar

- _quarto.yml
- stats.qmd
This pull request mainly added a section on statistical testing in python to stats.qmd based on the in class presentation delivered by John Ackerman. Additionally, it adds John Ackerman to the list of authors in _quarto.yml. 
Unfortunately some of the lines used to make tables exceeded 80 characters, and I was unable to find a way to resolve this without cutting information. Other than that I believe all writing matches the style of the rest of the source code.
> Added John Ackerman's section on statistical testing in python to stats.qmd.

- _variable_importance_metrics.qmd
made changes in accordance with feedback from first pull request
> merge updated variable importance metrics section

- _folium.qmd
- visualization.qmd
Here are three json files used in my presentation, necessary for the code to run. All of them combined weight about 5.5 MB:
[us_states.json](https://github.com/user-attachments/files/19787612/us_states.json)
[new-york-city-boroughs.json](https://github.com/user-attachments/files/19787632/new-york-city-boroughs.json)
[canada_provinces.json](https://github.com/user-attachments/files/19787633/canada_provinces.json)
> Vlad pushing topic presentation into classnotes; visualization chapter

- _quarto.yml
- optimal_clustering_notes.qmd
- references.bib
- requirements.txt
- unsupervised.qmd
I have added optimal_clustering_notes.qmd to the end of unsupervised.qmd
I have also added the gapstatistics module to the requirements.txt file and added my references to references.bib
> Nick added topic presentation on choosing the optimal number of clusters to class notes

- _shap.qmd
- index.qmd
This contribution adds a new section explaining how to interpret XGBoost predictions using SHAP. Simulated data was generated, and model behavior was visualized through SHAP plots. The content follows all required formatting guidelines.
> Add Section: Explaining XGBoost Predictions with SHAP
